// Code generated by sqlc. DO NOT EDIT.
// source: level.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createLevel = `-- name: CreateLevel :exec
INSERT INTO levels (id, name) VALUES ($1, $2)
`

type CreateLevelParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) CreateLevel(ctx context.Context, arg CreateLevelParams) error {
	_, err := q.db.ExecContext(ctx, createLevel, arg.ID, arg.Name)
	return err
}

const getLevelID = `-- name: GetLevelID :one
SELECT id FROM levels WHERE name = $1
`

func (q *Queries) GetLevelID(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getLevelID, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
