// Code generated by sqlc. DO NOT EDIT.
// source: payment.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const checkVA = `-- name: CheckVA :one
SELECT ca.id as comp_id, va.id as va_id, ca.wallet as wallet_id, va.va_key, va.domain FROM virtual_account va
LEFT JOIN companies_account ca ON va.id = ca.virtual_account
WHERE va_identity = $1
`

type CheckVARow struct {
	CompID   uuid.NullUUID `json:"comp_id"`
	VaID     uuid.UUID     `json:"va_id"`
	WalletID uuid.NullUUID `json:"wallet_id"`
	VaKey    string        `json:"va_key"`
	Domain   string        `json:"domain"`
}

func (q *Queries) CheckVA(ctx context.Context, vaIdentity int32) (CheckVARow, error) {
	row := q.db.QueryRowContext(ctx, checkVA, vaIdentity)
	var i CheckVARow
	err := row.Scan(
		&i.CompID,
		&i.VaID,
		&i.WalletID,
		&i.VaKey,
		&i.Domain,
	)
	return i, err
}

const payVA = `-- name: PayVA :exec
INSERT INTO va_payment (id, virtual_account, va_number, request_payment, paid_at) VALUES ($1, $2, $3, $4, DEFAULT)
`

type PayVAParams struct {
	ID             uuid.UUID `json:"id"`
	VirtualAccount uuid.UUID `json:"virtual_account"`
	VaNumber       string    `json:"va_number"`
	RequestPayment float64   `json:"request_payment"`
}

func (q *Queries) PayVA(ctx context.Context, arg PayVAParams) error {
	_, err := q.db.ExecContext(ctx, payVA,
		arg.ID,
		arg.VirtualAccount,
		arg.VaNumber,
		arg.RequestPayment,
	)
	return err
}

const updateBalance = `-- name: UpdateBalance :exec
UPDATE wallets SET balance = balance + $1 WHERE id = $2
`

type UpdateBalanceParams struct {
	Balance float64   `json:"balance"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateBalance, arg.Balance, arg.ID)
	return err
}
