// Code generated by sqlc. DO NOT EDIT.
// source: permission.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createPermissionLevel = `-- name: CreatePermissionLevel :exec
INSERT INTO permission_level (id, name) VALUES ($1, $2)
`

type CreatePermissionLevelParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) CreatePermissionLevel(ctx context.Context, arg CreatePermissionLevelParams) error {
	_, err := q.db.ExecContext(ctx, createPermissionLevel, arg.ID, arg.Name)
	return err
}

const getPermissionID = `-- name: GetPermissionID :one
SELECT id FROM permission_level WHERE name = $1
`

func (q *Queries) GetPermissionID(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getPermissionID, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
