// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: virtual_account.sql

package postgresql

import (
	"context"

	"github.com/google/uuid"
)

const issuePaymentVA = `-- name: IssuePaymentVA :exec
INSERT INTO issued_payment (id, virtual_account_id, virtual_account_number, payment_charge) VALUES ($1, $2, $3, $4)
`

type IssuePaymentVAParams struct {
	ID                   uuid.UUID `json:"id"`
	VirtualAccountID     uuid.UUID `json:"virtual_account_id"`
	VirtualAccountNumber int32     `json:"virtual_account_number"`
	PaymentCharge        float64   `json:"payment_charge"`
}

func (q *Queries) IssuePaymentVA(ctx context.Context, arg IssuePaymentVAParams) error {
	_, err := q.db.ExecContext(ctx, issuePaymentVA,
		arg.ID,
		arg.VirtualAccountID,
		arg.VirtualAccountNumber,
		arg.PaymentCharge,
	)
	return err
}
