// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: wallet.sql

package postgresql

import (
	"context"

	"github.com/google/uuid"
)

const addBalance = `-- name: AddBalance :execrows
UPDATE wallets SET balance = (balance + $1) WHERE id = $2
`

type AddBalanceParams struct {
	Balance float64   `json:"balance"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) AddBalance(ctx context.Context, arg AddBalanceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addBalance, arg.Balance, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const subtractBalance = `-- name: SubtractBalance :execrows
UPDATE wallets SET balance = (balance - $1) WHERE id = $2
`

type SubtractBalanceParams struct {
	Balance float64   `json:"balance"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) SubtractBalance(ctx context.Context, arg SubtractBalanceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, subtractBalance, arg.Balance, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
